export type Language = 'pt' | 'en' | 'es';

export interface Product {
  id: string;
  name: string;
  nameKey: string;
  image: string;
  imageSide?: string;
  imageFront?: string;
  color: string;
  descriptionKey: string;
  features?: string[];
}

export interface TranslationKey {
  // Navigation
  home: string;
  products: string;
  about: string;
  contact: string;
  language: string;
  portuguese: string;
  english: string;
  spanish: string;
  // Hero
  nicotine: string;
  heroTitle: string;
  heroSubtitle: string;
  heroDescription: string;
  letsTalk: string;
  // Proven Results / Purpose
  whyChooseUs: string;
  purposeTitle: string;
  purposeSubtitle: string;
  // Products
  productsTitle: string;
  productsSubtitle: string;
  productCoffee: string;
  productCoffeeDesc: string;
  productEnergy: string;
  productEnergyDesc: string;
  productMango: string;
  productMangoDesc: string;
  productWatermelon: string;
  productWatermelonDesc: string;
  productMenthol: string;
  productMentholDesc: string;
  learnMore: string;
  buyNow: string;
  // Technology
  technologyTitle: string;
  technologySubtitle: string;
  technologyDescription: string;
  techSelectedIngredients: string;
  techAdvancedTech: string;
  techPremiumQuality: string;
  techRigorousTesting: string;
  // Benefits
  benefitsTitle: string;
  benefitSaferTitle: string;
  benefitSaferDesc: string;
  benefitSuperiorTasteTitle: string;
  benefitSuperiorTasteDesc: string;
  benefitConvenienceTitle: string;
  benefitConvenienceDesc: string;
  benefitQualityTitle: string;
  benefitQualityDesc: string;
  // Stats
  statsUniqueFlavors: string;
  statsSatisfaction: string;
  statsTested: string;
  statsSupport: string;
  // How It Works
  howItWorksTitle: string;
  howStep1: string;
  howStep2: string;
  howStep3: string;
  howStep1Desc: string;
  howStep2Desc: string;
  howStep3Desc: string;
  // Testimonials
  testimonialsTitle: string;
  testimonialsSubtitle: string;
  // Mission
  missionTitle: string;
  missionText: string;
  missionSubtitle: string;
  // FAQ
  frequentlyAsked: string;
  questions: string;
  gotSomething: string;
  faq1Question: string;
  faq1Answer: string;
  faq2Question: string;
  faq2Answer: string;
  faq3Question: string;
  faq3Answer: string;
  faq4Question: string;
  faq4Answer: string;
  faq5Question: string;
  faq5Answer: string;
  faq6Question: string;
  faq6Answer: string;
  faq7Question: string;
  faq7Answer: string;
  // Social
  social: string;
  followAlong: string;
  // Footer
  newsletter: string;
  emailPlaceholder: string;
  siteMap: string;
  socialLinks: string;
  faq: string;
  termsOfService: string;
  privacyPolicy: string;
  legalNotice: string;
  ageRestriction: string;
  madeBy: string;
  lastUpdated: string;
  copyright: string;
  // Menu
  menuHome: string;
  menuProducts: string;
  menuAbout: string;
  menuContact: string;
}

export type Translations = Record<Language, TranslationKey>;
